// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQpoAKbcDplvp3WlNF-5gaZEdwtNSRsmI',
    appId: '1:627402656663:web:2ae7d38a8fbdccf0c052d2',
    messagingSenderId: '627402656663',
    projectId: 'portofolio-246c4',
    authDomain: 'portofolio-246c4.firebaseapp.com',
    storageBucket: 'portofolio-246c4.firebasestorage.app',
    measurementId: 'G-69TKB3TEVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRgXqibtnFLc2cfA-NHyADyLjO0DQE5yc',
    appId: '1:627402656663:android:cbc0aa24a543b8cfc052d2',
    messagingSenderId: '627402656663',
    projectId: 'portofolio-246c4',
    storageBucket: 'portofolio-246c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcP6dpkrng2sG_MOc65j8Fq6vvQx__koI',
    appId: '1:627402656663:ios:38247266fc47f5e2c052d2',
    messagingSenderId: '627402656663',
    projectId: 'portofolio-246c4',
    storageBucket: 'portofolio-246c4.firebasestorage.app',
    iosBundleId: 'com.portfolio.portfolio',
  );
}
